### ISSUE TITLE
Crash when clicking on a model with no namespace in the identifier

### ISSUE THREAD

**Issue by Hugman76** [VanillaChai/minecraft-resource-manager#1]
If you have a blockstate with a model referencing an ID with no namespace (which is `minecraft` by default), the whole software crashes
![image](https://user-images.githubusercontent.com/36963654/114378485-0b289a80-9b88-11eb-8591-4f6f076486bb.png)

**Comment by VanillaChai** [comment]
Oops, I forgot you can omit the `minecraft` namespace, this should hopefully be quick to fix.
